name: flutter_sanity
description: Flutter library for Sanity.io
version: 0.1.0
homepage: https://github.com/joelrose/flutter_sanity
repository: https://github.com/joelrose/flutter_sanity

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  http: ^0.13.4
